spring:
  application:
    name: 'pizzaria-api'
  data:
    mongodb:
      uri: 'mongodb+srv://brigido:brigidopassword@clusterpizzaria.9newe.mongodb.net/pizzariadb?retryWrites=true&w=majority&appName=ClusterPizzaria'
      auto-index-creation: true